# Variable Group 'VG-DEV' was defined in the Variables tab
trigger:
- main
variables:
  -group: 'VG-DEV'
stages:
  - stage: 'DeployDEV'
    displayName: 'Deploy to DEV environment'
    jobs:
    - deployment: Deploy
      displayName: 'Self hosted Agent job'
      pool:
       vmImage: 'ubuntu-latest'
      environment: 'dev_env'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureCLI@2
                displayName: 'Artifact Deploy To Azure Container'
                inputs:
                  azureSubscription: 'AZDatalakeServiceConnection'
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    echo "azcopy login with SP"
                    
                    
                                      export AZCOPY_SPA_CLIENT_SECRET=$(client-secret)
                    
                                      /home/datalake1/azcopy/azcopy_linux_amd64_10.10.0/azcopy login --service-principal --application-id $(clientid) --tenant-id=$(tenentid)
                    
                    
                                      echo "azcopy Artifact to ADLS"
                    
                    
                                      /home/datalake1/azcopy/azcopy_linux_amd64_10.10.0/azcopy copy "$(System.DefaultWorkingDirectory)/nwrlc/" "https://$(target-storage).dfs.core.windows.net/$(target-container)/DBPP/" --include-path "code/bin/py/Sparkpostprocess.py;code/bin/py/customPurge.py"  --recursive=true
                                      echo "azcopy Artifact to ADLS2"
                                      /home/datalake1/azcopy/azcopy_linux_amd64_10.10.0/azcopy copy "$(System.DefaultWorkingDirectory)/nwrlc/" "https://$(target-storage).dfs.core.windows.net/$(target-container)/DBPP/" --include-path "config/postprocessConf.json;config/columnMapping.csv"  --recursive=true
                  addSpnToEnvironment: true
                  useGlobalConfig: true
              - task: SSH@0
                displayName: 'Run shell commands on Target machine'
                inputs:
                  sshEndpoint: 'targetvm'
                  runOptions: 'commands'
                  commands: |
                    mkdir -p /home/datalake1/Environment/dev/dbpp/common; 
                    mkdir -p /home/datalake1/Environment/dev/dbpp/nwrlc; 
                    mkdir -p /home/datalake1/Environment/dev/dbpp/scalaApp;
                  readyTimeout: '20000'
              - task: CopyFilesOverSSH@0
                displayName: 'Artifact Deploy to Azure VM'
                inputs:
                  sshEndpoint: 'targetvm'
                  sourceFolder: '$(System.DefaultWorkingDirectory)/nwrlc'
                  contents: |
                    /code/bin/*.sh*
                    /tws/*.shed*
                  targetFolder: '/home/datalake1/Environment/dev/dbpp/nwrlc'
                  readyTimeout: '20000'